### ISSUE TITLE
05.09 오후

### ISSUE THREAD

**Issue by Chungyeop** [milttang/Calculator#6]
1. 2 진수 결과 값을 이미지로 표현 시 String 배열 첫 인덱스에 null 값이 포함되어, 임시로 다음과 같이 문제를 해결했습니다.

    String[] binaryArray = resultNum.split("");

    String[] binaryArray2 = Arrays.copyOfRange(binaryArray, 1, binaryArray.length);

    기존의 binaryArray에서 binaryArray[0]을 제외한 배열 binaryArray2를 새로 만들어 결과 값에 반영.

    ex) 결과 값이 10 진수로 2 일 때, 2 진수로는 10 이므로, String 배열인 binaryArray에는 [1,0] 으로 표시되어야 하지만,
      Andorid 4.4 버전에서는 [,1,0] 으로 표시되어 나와 결과 값 이미지 적용 시 문제 발생.

    String 배열에 있는 null 값을 제거하는 방법이 Best 일 것 같은데, 가능한 방법이 있다면 수정해서 적용 부탁드립니다.

**Comment by milttang** [comment]
해당 부분 밑에 새로 만드신 if 중첩문 없어도 기능구현에 문제없던데 따로 필요한 코드인가요??

**Comment by Chungyeop** [comment]
AND, OR, XOR 과 같은 비트 연산의 경우 기존의 입력 값보다 결과 값의 길이가 작은 경우가 많이 발생하여 if 조건문을 사용하였습니다. IF 조건문을 따로 사용하지 않을 경우 결과 값의 이미지가 모두 지워지지 않는 에러가 발생되게 됩니다.
